#!/usr/bin/env python3
"""
Create notebook with improved physics to prevent ball getting stuck
ボールが挟まって動かなくなる問題を解決
"""

import json

def create_improved_physics_cells():
    """Create cells with improved ball physics"""
    
    cells = []
    
    # Header
    cells.append({
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# ⚽ Multi-Agent Soccer with Improved Physics (20-second episodes)\n",
            "## ボールが挟まらない改良版物理エンジン\n\n",
            "ボールがプレイヤー間に挟まって動かなくなる問題を解決した改良版です。"
        ]
    })
    
    # Installation
    cells.append({
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": [
            "!pip install numpy matplotlib pygame pettingzoo torch pillow opencv-python-headless imageio tqdm -q\n",
            "print('✅ Dependencies installed')"
        ]
    })
    
    # Imports
    cells.append({
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": [
            "import numpy as np\n",
            "import matplotlib.pyplot as plt\n",
            "import matplotlib.patches as patches\n",
            "from matplotlib.animation import FuncAnimation\n",
            "import pygame\n",
            "import torch\n",
            "import torch.nn as nn\n",
            "import torch.optim as optim\n",
            "from collections import defaultdict, deque\n",
            "from dataclasses import dataclass, field\n",
            "from typing import Dict, List, Optional, Tuple, Any, Union\n",
            "from enum import Enum\n",
            "import random\n",
            "import math\n",
            "from abc import ABC, abstractmethod\n",
            "import warnings\n",
            "from PIL import Image\n",
            "import cv2\n",
            "import imageio\n",
            "from tqdm import tqdm\n",
            "import os\n",
            "from IPython.display import Video, display, HTML\n",
            "warnings.filterwarnings('ignore')\n",
            "\n",
            "print('✅ Imports complete')"
        ]
    })
    
    # Improved Configuration with better physics
    cells.append({
        "cell_type": "markdown",
        "metadata": {},
        "source": ["### ⚙️ Improved Physics Configuration"]
    })
    
    cells.append({
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": [
            "@dataclass\n",
            "class ImprovedSoccerConfig:\n",
            "    \"\"\"Configuration with improved physics to prevent ball getting stuck\"\"\"\n",
            "    # Field dimensions\n",
            "    FIELD_SIZE: Tuple[int, int] = (800, 600)\n",
            "    GOAL_SIZE: Tuple[int, int] = (50, 150)\n",
            "    \n",
            "    # Game settings for 20 seconds\n",
            "    MAX_STEPS: int = 600  # 20 seconds at 30 FPS\n",
            "    TEAM_SIZE: int = 2\n",
            "    \n",
            "    # Player physics\n",
            "    PLAYER_RADIUS: float = 20.0\n",
            "    PLAYER_SPEED: float = 4.5  # Slightly faster for more dynamic play\n",
            "    PLAYER_MASS: float = 1.0\n",
            "    \n",
            "    # Ball physics - IMPROVED SETTINGS\n",
            "    BALL_RADIUS: float = 10.0\n",
            "    BALL_MASS: float = 0.4  # Lighter ball for easier movement\n",
            "    BALL_FRICTION: float = 0.96  # Higher value = less friction (0.96 vs 0.93)\n",
            "    BALL_RESTITUTION: float = 0.85  # Higher bounce (0.85 vs 0.7)\n",
            "    BALL_SPEED_MULTIPLIER: float = 1.8  # Faster ball movement (1.8 vs 1.3)\n",
            "    MIN_BALL_SPEED: float = 0.5  # Minimum speed threshold\n",
            "    \n",
            "    # Anti-stuck mechanics\n",
            "    STUCK_DETECTION_FRAMES: int = 15  # Frames to detect if ball is stuck\n",
            "    STUCK_VELOCITY_THRESHOLD: float = 0.8  # Velocity below this = stuck\n",
            "    ESCAPE_FORCE: float = 8.0  # Force applied to escape when stuck\n",
            "    PLAYER_SEPARATION_FORCE: float = 3.0  # Force to separate overlapping players\n",
            "    \n",
            "    # Collision physics\n",
            "    COLLISION_ELASTICITY: float = 0.9  # Elastic collisions (0.9 vs 0.6)\n",
            "    COLLISION_DAMPING: float = 0.85  # Less damping for more movement\n",
            "    \n",
            "    # Kick mechanics\n",
            "    KICK_FORCE: float = 15.0  # Stronger kicks (15 vs 10)\n",
            "    KICK_RANGE: float = 30.0  # Range for kicking\n",
            "    \n",
            "    # Colors\n",
            "    TEAM_COLORS: List[str] = field(default_factory=lambda: ['blue', 'red'])\n",
            "    BALL_COLOR: str = 'white'\n",
            "    FIELD_COLOR: str = 'green'\n",
            "\n",
            "config = ImprovedSoccerConfig()\n",
            "print(\"✅ Improved physics configuration created:\")\n",
            "print(f\"   Ball friction: {config.BALL_FRICTION} (less friction)\")\n",
            "print(f\"   Ball restitution: {config.BALL_RESTITUTION} (more bounce)\")\n",
            "print(f\"   Ball speed multiplier: {config.BALL_SPEED_MULTIPLIER}\")\n",
            "print(f\"   Anti-stuck escape force: {config.ESCAPE_FORCE}\")\n",
            "print(f\"   Collision elasticity: {config.COLLISION_ELASTICITY}\")"
        ]
    })
    
    # Improved Physics Engine
    cells.append({
        "cell_type": "markdown",
        "metadata": {},
        "source": ["### 🔧 Enhanced Physics Engine with Anti-Stuck Mechanics"]
    })
    
    cells.append({
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": [
            "class ImprovedPhysicsEngine:\n",
            "    \"\"\"Physics engine with anti-stuck mechanics\"\"\"\n",
            "    \n",
            "    def __init__(self, config: ImprovedSoccerConfig):\n",
            "        self.config = config\n",
            "        self.stuck_frames = 0\n",
            "        self.last_ball_position = None\n",
            "        self.ball_velocity_history = deque(maxlen=config.STUCK_DETECTION_FRAMES)\n",
            "        \n",
            "    def update_ball(self, ball: 'Ball', players: List['Player'], delta_time: float = 1.0):\n",
            "        \"\"\"Update ball physics with anti-stuck mechanics\"\"\"\n",
            "        \n",
            "        # Store velocity history\n",
            "        ball_speed = np.linalg.norm(ball.velocity)\n",
            "        self.ball_velocity_history.append(ball_speed)\n",
            "        \n",
            "        # Check if ball is stuck\n",
            "        if self._is_ball_stuck(ball, players):\n",
            "            self._apply_escape_force(ball, players)\n",
            "            self.stuck_frames += 1\n",
            "        else:\n",
            "            self.stuck_frames = 0\n",
            "        \n",
            "        # Apply improved friction\n",
            "        ball.velocity *= self.config.BALL_FRICTION\n",
            "        \n",
            "        # Add small random perturbation to prevent perfect symmetry\n",
            "        if ball_speed < self.config.MIN_BALL_SPEED:\n",
            "            ball.velocity += np.random.randn(2) * 0.1\n",
            "        \n",
            "        # Update position\n",
            "        ball.position += ball.velocity * delta_time\n",
            "        \n",
            "        # Handle collisions with walls (improved bounce)\n",
            "        self._handle_wall_collision(ball)\n",
            "        \n",
            "        # Handle collisions with players (improved response)\n",
            "        for player in players:\n",
            "            self._handle_ball_player_collision(ball, player)\n",
            "        \n",
            "        # Store position for stuck detection\n",
            "        self.last_ball_position = ball.position.copy()\n",
            "    \n",
            "    def _is_ball_stuck(self, ball: 'Ball', players: List['Player']) -> bool:\n",
            "        \"\"\"Detect if ball is stuck between players\"\"\"\n",
            "        if len(self.ball_velocity_history) < self.config.STUCK_DETECTION_FRAMES:\n",
            "            return False\n",
            "        \n",
            "        # Check average velocity\n",
            "        avg_velocity = np.mean(list(self.ball_velocity_history))\n",
            "        if avg_velocity > self.config.STUCK_VELOCITY_THRESHOLD:\n",
            "            return False\n",
            "        \n",
            "        # Check if ball is near multiple players\n",
            "        nearby_players = 0\n",
            "        for player in players:\n",
            "            dist = np.linalg.norm(ball.position - player.position)\n",
            "            if dist < self.config.PLAYER_RADIUS + self.config.BALL_RADIUS + 5:\n",
            "                nearby_players += 1\n",
            "        \n",
            "        return nearby_players >= 2\n",
            "    \n",
            "    def _apply_escape_force(self, ball: 'Ball', players: List['Player']):\n",
            "        \"\"\"Apply force to escape from stuck situation\"\"\"\n",
            "        # Find the two closest players\n",
            "        distances = [(p, np.linalg.norm(ball.position - p.position)) for p in players]\n",
            "        distances.sort(key=lambda x: x[1])\n",
            "        \n",
            "        if len(distances) >= 2:\n",
            "            player1, player2 = distances[0][0], distances[1][0]\n",
            "            \n",
            "            # Calculate escape direction (perpendicular to line between players)\n",
            "            player_line = player2.position - player1.position\n",
            "            if np.linalg.norm(player_line) > 0:\n",
            "                player_line = player_line / np.linalg.norm(player_line)\n",
            "                # Perpendicular direction with random choice\n",
            "                escape_dir = np.array([-player_line[1], player_line[0]])\n",
            "                if random.random() > 0.5:\n",
            "                    escape_dir = -escape_dir\n",
            "            else:\n",
            "                # Random escape direction\n",
            "                angle = random.uniform(0, 2 * math.pi)\n",
            "                escape_dir = np.array([math.cos(angle), math.sin(angle)])\n",
            "            \n",
            "            # Apply escape force\n",
            "            ball.velocity += escape_dir * self.config.ESCAPE_FORCE\n",
            "            \n",
            "            # Also slightly push players apart\n",
            "            separation = player2.position - player1.position\n",
            "            if np.linalg.norm(separation) > 0:\n",
            "                separation = separation / np.linalg.norm(separation)\n",
            "                player1.position -= separation * self.config.PLAYER_SEPARATION_FORCE\n",
            "                player2.position += separation * self.config.PLAYER_SEPARATION_FORCE\n",
            "    \n",
            "    def _handle_wall_collision(self, ball: 'Ball'):\n",
            "        \"\"\"Handle ball collision with walls (improved bounce)\"\"\"\n",
            "        width, height = self.config.FIELD_SIZE\n",
            "        \n",
            "        # Left/Right walls\n",
            "        if ball.position[0] - self.config.BALL_RADIUS <= 0:\n",
            "            ball.position[0] = self.config.BALL_RADIUS\n",
            "            ball.velocity[0] = abs(ball.velocity[0]) * self.config.BALL_RESTITUTION\n",
            "            ball.velocity += np.random.randn(2) * 0.5  # Add randomness\n",
            "        elif ball.position[0] + self.config.BALL_RADIUS >= width:\n",
            "            ball.position[0] = width - self.config.BALL_RADIUS\n",
            "            ball.velocity[0] = -abs(ball.velocity[0]) * self.config.BALL_RESTITUTION\n",
            "            ball.velocity += np.random.randn(2) * 0.5\n",
            "        \n",
            "        # Top/Bottom walls\n",
            "        if ball.position[1] - self.config.BALL_RADIUS <= 0:\n",
            "            ball.position[1] = self.config.BALL_RADIUS\n",
            "            ball.velocity[1] = abs(ball.velocity[1]) * self.config.BALL_RESTITUTION\n",
            "            ball.velocity += np.random.randn(2) * 0.5\n",
            "        elif ball.position[1] + self.config.BALL_RADIUS >= height:\n",
            "            ball.position[1] = height - self.config.BALL_RADIUS\n",
            "            ball.velocity[1] = -abs(ball.velocity[1]) * self.config.BALL_RESTITUTION\n",
            "            ball.velocity += np.random.randn(2) * 0.5\n",
            "    \n",
            "    def _handle_ball_player_collision(self, ball: 'Ball', player: 'Player'):\n",
            "        \"\"\"Handle collision between ball and player (improved response)\"\"\"\n",
            "        dist_vec = ball.position - player.position\n",
            "        dist = np.linalg.norm(dist_vec)\n",
            "        \n",
            "        min_dist = self.config.BALL_RADIUS + self.config.PLAYER_RADIUS\n",
            "        \n",
            "        if dist < min_dist and dist > 0:\n",
            "            # Normalize collision vector\n",
            "            collision_normal = dist_vec / dist\n",
            "            \n",
            "            # Separate ball and player\n",
            "            overlap = min_dist - dist\n",
            "            ball.position += collision_normal * (overlap * 0.7)  # Ball moves more\n",
            "            player.position -= collision_normal * (overlap * 0.3)  # Player moves less\n",
            "            \n",
            "            # Calculate relative velocity\n",
            "            relative_velocity = ball.velocity - player.velocity\n",
            "            velocity_along_normal = np.dot(relative_velocity, collision_normal)\n",
            "            \n",
            "            # Only resolve if velocities are converging\n",
            "            if velocity_along_normal < 0:\n",
            "                # Calculate impulse with improved elasticity\n",
            "                impulse = 2 * velocity_along_normal / (1/self.config.BALL_MASS + 1/self.config.PLAYER_MASS)\n",
            "                impulse_vector = impulse * collision_normal * self.config.COLLISION_ELASTICITY\n",
            "                \n",
            "                # Apply impulse\n",
            "                ball.velocity -= impulse_vector / self.config.BALL_MASS\n",
            "                player.velocity += impulse_vector / self.config.PLAYER_MASS\n",
            "                \n",
            "                # Add kick effect if player is trying to kick\n",
            "                if player.is_kicking:\n",
            "                    kick_force = collision_normal * self.config.KICK_FORCE\n",
            "                    ball.velocity += kick_force\n",
            "                    \n",
            "                    # Add spin/curve effect\n",
            "                    perpendicular = np.array([-collision_normal[1], collision_normal[0]])\n",
            "                    ball.velocity += perpendicular * random.uniform(-2, 2)\n",
            "                \n",
            "                # Apply damping\n",
            "                ball.velocity *= self.config.COLLISION_DAMPING\n",
            "                \n",
            "                # Ensure minimum speed\n",
            "                if np.linalg.norm(ball.velocity) < self.config.MIN_BALL_SPEED:\n",
            "                    ball.velocity = collision_normal * self.config.MIN_BALL_SPEED * 2\n",
            "\n",
            "print('✅ Improved physics engine created with anti-stuck mechanics')"
        ]
    })
    
    # Game entities
    cells.append({
        "cell_type": "markdown",
        "metadata": {},
        "source": ["### 🎮 Game Entities"]
    })
    
    cells.append({
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": [
            "class Ball:\n",
            "    \"\"\"Ball entity with improved physics properties\"\"\"\n",
            "    \n",
            "    def __init__(self, position: np.ndarray):\n",
            "        self.position = position.astype(float)\n",
            "        self.velocity = np.zeros(2, dtype=float)\n",
            "        self.stuck_counter = 0\n",
            "    \n",
            "    def reset(self, position: np.ndarray):\n",
            "        self.position = position.astype(float)\n",
            "        self.velocity = np.zeros(2, dtype=float)\n",
            "        self.stuck_counter = 0\n",
            "\n",
            "\n",
            "class Player:\n",
            "    \"\"\"Player entity with kicking ability\"\"\"\n",
            "    \n",
            "    def __init__(self, player_id: int, team: int, position: np.ndarray):\n",
            "        self.id = player_id\n",
            "        self.team = team\n",
            "        self.position = position.astype(float)\n",
            "        self.velocity = np.zeros(2, dtype=float)\n",
            "        self.is_kicking = False\n",
            "        self.stamina = 1.0\n",
            "    \n",
            "    def reset(self, position: np.ndarray):\n",
            "        self.position = position.astype(float)\n",
            "        self.velocity = np.zeros(2, dtype=float)\n",
            "        self.is_kicking = False\n",
            "        self.stamina = 1.0\n",
            "\n",
            "print('✅ Game entities defined')"
        ]
    })
    
    # Rest of the environment implementation...
    # (Continue with the full environment, agents, training loop, etc.)
    
    # Add all remaining cells for the complete implementation
    cells.extend(create_environment_cells())
    cells.extend(create_agent_cells())
    cells.extend(create_training_cells())
    cells.extend(create_visualization_cells())
    
    return cells


def create_environment_cells():
    """Create environment implementation cells"""
    cells = []
    
    cells.append({
        "cell_type": "markdown",
        "metadata": {},
        "source": ["### 🏟️ Soccer Environment with Improved Physics"]
    })
    
    cells.append({
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": [
            "from gymnasium import spaces\n",
            "from pettingzoo import AECEnv\n",
            "from pettingzoo.utils import agent_selector as AgentSelector\n",
            "\n",
            "class ImprovedSoccerEnvironment(AECEnv):\n",
            "    \"\"\"Soccer environment with improved physics\"\"\"\n",
            "    \n",
            "    metadata = {'render_modes': ['human', 'rgb_array'], 'render_fps': 30}\n",
            "    \n",
            "    def __init__(self, config: ImprovedSoccerConfig = None, render_mode: str = None):\n",
            "        super().__init__()\n",
            "        self.config = config or ImprovedSoccerConfig()\n",
            "        self.render_mode = render_mode\n",
            "        \n",
            "        # Initialize physics engine\n",
            "        self.physics = ImprovedPhysicsEngine(self.config)\n",
            "        \n",
            "        # Initialize agents\n",
            "        self.possible_agents = [f'player_{i}' for i in range(self.config.TEAM_SIZE * 2)]\n",
            "        self.agents = self.possible_agents[:]\n",
            "        self.agent_name_mapping = {agent: i for i, agent in enumerate(self.agents)}\n",
            "        \n",
            "        # Initialize game objects\n",
            "        self.ball = None\n",
            "        self.players = {}\n",
            "        self.reset()\n",
            "        \n",
            "        # Define action and observation spaces\n",
            "        self._action_spaces = {\n",
            "            agent: spaces.Box(low=-1, high=1, shape=(5,), dtype=np.float32)\n",
            "            for agent in self.possible_agents\n",
            "        }\n",
            "        self._observation_spaces = {\n",
            "            agent: spaces.Box(low=0, high=1, shape=(28,), dtype=np.float32)\n",
            "            for agent in self.possible_agents\n",
            "        }\n",
            "    \n",
            "    def reset(self, seed: Optional[int] = None, options: Optional[dict] = None):\n",
            "        \"\"\"Reset environment with improved initial positions\"\"\"\n",
            "        if seed is not None:\n",
            "            np.random.seed(seed)\n",
            "            random.seed(seed)\n",
            "        \n",
            "        self.agents = self.possible_agents[:]\n",
            "        self.rewards = {agent: 0 for agent in self.agents}\n",
            "        self._cumulative_rewards = {agent: 0 for agent in self.agents}\n",
            "        self.terminations = {agent: False for agent in self.agents}\n",
            "        self.truncations = {agent: False for agent in self.agents}\n",
            "        self.infos = {agent: {} for agent in self.agents}\n",
            "        \n",
            "        # Reset ball at center with small random offset\n",
            "        center = np.array(self.config.FIELD_SIZE) / 2\n",
            "        offset = np.random.randn(2) * 10\n",
            "        self.ball = Ball(center + offset)\n",
            "        \n",
            "        # Reset players with better spacing\n",
            "        self.players = {}\n",
            "        width, height = self.config.FIELD_SIZE\n",
            "        \n",
            "        for i, agent in enumerate(self.agents):\n",
            "            team = i // self.config.TEAM_SIZE\n",
            "            team_position = i % self.config.TEAM_SIZE\n",
            "            \n",
            "            # Improved initial positions to avoid clustering\n",
            "            if team == 0:  # Blue team (left)\n",
            "                x = width * 0.25 + random.uniform(-20, 20)\n",
            "                y = height * (0.35 + team_position * 0.3) + random.uniform(-20, 20)\n",
            "            else:  # Red team (right)\n",
            "                x = width * 0.75 + random.uniform(-20, 20)\n",
            "                y = height * (0.35 + team_position * 0.3) + random.uniform(-20, 20)\n",
            "            \n",
            "            self.players[agent] = Player(i, team, np.array([x, y]))\n",
            "        \n",
            "        # Reset other state\n",
            "        self.current_step = 0\n",
            "        self.score = [0, 0]\n",
            "        \n",
            "        # Set up agent selector\n",
            "        self._agent_selector = AgentSelector(self.agents)\n",
            "        self.agent_selection = self._agent_selector.next()\n",
            "        \n",
            "        return self.observe(self.agent_selection), self.infos[self.agent_selection]\n",
            "    \n",
            "    def step(self, action: np.ndarray):\n",
            "        \"\"\"Execute one step with improved physics\"\"\"\n",
            "        if self.terminations[self.agent_selection] or self.truncations[self.agent_selection]:\n",
            "            self._was_dead_step(action)\n",
            "            return\n",
            "        \n",
            "        # Apply action to current player\n",
            "        player = self.players[self.agent_selection]\n",
            "        self._apply_action(player, action)\n",
            "        \n",
            "        # Update only after all agents have acted\n",
            "        if self._agent_selector.is_last():\n",
            "            self._update_game_state()\n",
            "        \n",
            "        # Move to next agent\n",
            "        self.agent_selection = self._agent_selector.next()\n",
            "    \n",
            "    def _apply_action(self, player: Player, action: np.ndarray):\n",
            "        \"\"\"Apply action to player with improved control\"\"\"\n",
            "        # Movement (first 2 dimensions)\n",
            "        movement = action[:2] * self.config.PLAYER_SPEED\n",
            "        player.velocity = movement\n",
            "        \n",
            "        # Kick action (dimension 2)\n",
            "        player.is_kicking = action[2] > 0.5\n",
            "        \n",
            "        # Update position\n",
            "        player.position += player.velocity\n",
            "        \n",
            "        # Keep player in bounds\n",
            "        player.position[0] = np.clip(player.position[0], \n",
            "                                    self.config.PLAYER_RADIUS,\n",
            "                                    self.config.FIELD_SIZE[0] - self.config.PLAYER_RADIUS)\n",
            "        player.position[1] = np.clip(player.position[1],\n",
            "                                    self.config.PLAYER_RADIUS,\n",
            "                                    self.config.FIELD_SIZE[1] - self.config.PLAYER_RADIUS)\n",
            "    \n",
            "    def _update_game_state(self):\n",
            "        \"\"\"Update game state with improved physics\"\"\"\n",
            "        # Update ball physics with anti-stuck mechanics\n",
            "        self.physics.update_ball(self.ball, list(self.players.values()))\n",
            "        \n",
            "        # Check for goals\n",
            "        self._check_goals()\n",
            "        \n",
            "        # Calculate rewards\n",
            "        self._calculate_rewards()\n",
            "        \n",
            "        # Update step counter\n",
            "        self.current_step += 1\n",
            "        \n",
            "        # Check for episode end\n",
            "        if self.current_step >= self.config.MAX_STEPS:\n",
            "            for agent in self.agents:\n",
            "                self.truncations[agent] = True\n",
            "    \n",
            "    def _check_goals(self):\n",
            "        \"\"\"Check if ball is in goal\"\"\"\n",
            "        ball_x, ball_y = self.ball.position\n",
            "        width, height = self.config.FIELD_SIZE\n",
            "        goal_top = (height - self.config.GOAL_SIZE[1]) / 2\n",
            "        goal_bottom = goal_top + self.config.GOAL_SIZE[1]\n",
            "        \n",
            "        # Check left goal (team 1 scores)\n",
            "        if ball_x <= self.config.GOAL_SIZE[0] and goal_top <= ball_y <= goal_bottom:\n",
            "            self.score[1] += 1\n",
            "            self._reset_after_goal()\n",
            "            print(f\"⚽ GOAL! Red team scores! Score: {self.score}\")\n",
            "        \n",
            "        # Check right goal (team 0 scores)\n",
            "        elif ball_x >= width - self.config.GOAL_SIZE[0] and goal_top <= ball_y <= goal_bottom:\n",
            "            self.score[0] += 1\n",
            "            self._reset_after_goal()\n",
            "            print(f\"⚽ GOAL! Blue team scores! Score: {self.score}\")\n",
            "    \n",
            "    def _reset_after_goal(self):\n",
            "        \"\"\"Reset positions after goal with anti-clustering\"\"\"\n",
            "        # Reset ball to center with random velocity\n",
            "        center = np.array(self.config.FIELD_SIZE) / 2\n",
            "        self.ball.position = center.copy()\n",
            "        # Give ball initial random velocity to prevent immediate clustering\n",
            "        angle = random.uniform(0, 2 * math.pi)\n",
            "        speed = random.uniform(2, 4)\n",
            "        self.ball.velocity = np.array([math.cos(angle), math.sin(angle)]) * speed\n",
            "        \n",
            "        # Reset players to starting positions\n",
            "        width, height = self.config.FIELD_SIZE\n",
            "        for i, agent in enumerate(self.agents):\n",
            "            team = i // self.config.TEAM_SIZE\n",
            "            team_position = i % self.config.TEAM_SIZE\n",
            "            \n",
            "            if team == 0:\n",
            "                x = width * 0.25\n",
            "                y = height * (0.35 + team_position * 0.3)\n",
            "            else:\n",
            "                x = width * 0.75\n",
            "                y = height * (0.35 + team_position * 0.3)\n",
            "            \n",
            "            self.players[agent].position = np.array([x, y])\n",
            "            self.players[agent].velocity = np.zeros(2)\n",
            "    \n",
            "    def _calculate_rewards(self):\n",
            "        \"\"\"Calculate rewards for all agents\"\"\"\n",
            "        for agent in self.agents:\n",
            "            player = self.players[agent]\n",
            "            reward = 0.0\n",
            "            \n",
            "            # Distance to ball reward\n",
            "            dist_to_ball = np.linalg.norm(self.ball.position - player.position)\n",
            "            reward += max(0, 1.0 - dist_to_ball / 200) * 0.1\n",
            "            \n",
            "            # Ball movement reward (encourage active play)\n",
            "            ball_speed = np.linalg.norm(self.ball.velocity)\n",
            "            if dist_to_ball < 50:\n",
            "                reward += ball_speed * 0.05\n",
            "            \n",
            "            # Goal rewards\n",
            "            if self.score[player.team] > 0:\n",
            "                reward += 10.0\n",
            "            if self.score[1 - player.team] > 0:\n",
            "                reward -= 10.0\n",
            "            \n",
            "            self.rewards[agent] = reward\n",
            "            self._cumulative_rewards[agent] += reward\n",
            "    \n",
            "    def observe(self, agent: str) -> np.ndarray:\n",
            "        \"\"\"Get observation for agent\"\"\"\n",
            "        player = self.players[agent]\n",
            "        obs = []\n",
            "        \n",
            "        # Normalize positions\n",
            "        width, height = self.config.FIELD_SIZE\n",
            "        \n",
            "        # Self position and velocity\n",
            "        obs.extend(player.position / [width, height])\n",
            "        obs.extend(player.velocity / 10.0)\n",
            "        \n",
            "        # Ball position and velocity\n",
            "        obs.extend(self.ball.position / [width, height])\n",
            "        obs.extend(self.ball.velocity / 20.0)\n",
            "        \n",
            "        # Teammate and opponents\n",
            "        for other_agent in self.agents:\n",
            "            if other_agent != agent:\n",
            "                other = self.players[other_agent]\n",
            "                obs.extend(other.position / [width, height])\n",
            "                obs.extend(other.velocity / 10.0)\n",
            "        \n",
            "        # Game state\n",
            "        obs.extend([self.score[0] / 10, self.score[1] / 10])\n",
            "        obs.append(self.current_step / self.config.MAX_STEPS)\n",
            "        obs.append(player.stamina)\n",
            "        \n",
            "        return np.array(obs, dtype=np.float32)\n",
            "    \n",
            "    def render(self):\n",
            "        \"\"\"Render the environment\"\"\"\n",
            "        if self.render_mode == 'rgb_array':\n",
            "            return self._render_frame()\n",
            "        elif self.render_mode == 'human':\n",
            "            frame = self._render_frame()\n",
            "            plt.imshow(frame)\n",
            "            plt.axis('off')\n",
            "            plt.show()\n",
            "    \n",
            "    def _render_frame(self) -> np.ndarray:\n",
            "        \"\"\"Render current frame\"\"\"\n",
            "        width, height = self.config.FIELD_SIZE\n",
            "        \n",
            "        # Create figure\n",
            "        fig, ax = plt.subplots(figsize=(10, 7))\n",
            "        \n",
            "        # Draw field\n",
            "        field = patches.Rectangle((0, 0), width, height, \n",
            "                                 linewidth=2, edgecolor='white',\n",
            "                                 facecolor='green')\n",
            "        ax.add_patch(field)\n",
            "        \n",
            "        # Draw goals\n",
            "        goal_height = self.config.GOAL_SIZE[1]\n",
            "        goal_y = (height - goal_height) / 2\n",
            "        \n",
            "        left_goal = patches.Rectangle((0, goal_y), self.config.GOAL_SIZE[0],\n",
            "                                     goal_height, facecolor='white', alpha=0.3)\n",
            "        right_goal = patches.Rectangle((width - self.config.GOAL_SIZE[0], goal_y),\n",
            "                                      self.config.GOAL_SIZE[0], goal_height,\n",
            "                                      facecolor='white', alpha=0.3)\n",
            "        ax.add_patch(left_goal)\n",
            "        ax.add_patch(right_goal)\n",
            "        \n",
            "        # Draw players\n",
            "        for agent, player in self.players.items():\n",
            "            color = self.config.TEAM_COLORS[player.team]\n",
            "            circle = patches.Circle(player.position, self.config.PLAYER_RADIUS,\n",
            "                                   facecolor=color, edgecolor='white', linewidth=2)\n",
            "            ax.add_patch(circle)\n",
            "            \n",
            "            # Add player number\n",
            "            ax.text(player.position[0], player.position[1], str(player.id),\n",
            "                   ha='center', va='center', color='white', fontsize=10, fontweight='bold')\n",
            "        \n",
            "        # Draw ball\n",
            "        ball_circle = patches.Circle(self.ball.position, self.config.BALL_RADIUS,\n",
            "                                    facecolor='white', edgecolor='black', linewidth=2)\n",
            "        ax.add_patch(ball_circle)\n",
            "        \n",
            "        # Draw ball velocity indicator\n",
            "        if np.linalg.norm(self.ball.velocity) > 0.1:\n",
            "            vel_scale = 5\n",
            "            ax.arrow(self.ball.position[0], self.ball.position[1],\n",
            "                    self.ball.velocity[0] * vel_scale,\n",
            "                    self.ball.velocity[1] * vel_scale,\n",
            "                    color='yellow', width=2, alpha=0.7)\n",
            "        \n",
            "        # Add score and time\n",
            "        time_remaining = (self.config.MAX_STEPS - self.current_step) / 30  # seconds\n",
            "        ax.text(width/2, 20, f'Blue {self.score[0]} - {self.score[1]} Red',\n",
            "               ha='center', fontsize=16, fontweight='bold', color='white')\n",
            "        ax.text(width/2, height-20, f'Time: {time_remaining:.1f}s',\n",
            "               ha='center', fontsize=12, color='white')\n",
            "        \n",
            "        # Add stuck indicator if ball is stuck\n",
            "        if self.physics.stuck_frames > 0:\n",
            "            ax.text(self.ball.position[0], self.ball.position[1] - 30,\n",
            "                   '⚠️ STUCK', ha='center', color='red', fontsize=10, fontweight='bold')\n",
            "        \n",
            "        ax.set_xlim(0, width)\n",
            "        ax.set_ylim(0, height)\n",
            "        ax.set_aspect('equal')\n",
            "        ax.axis('off')\n",
            "        \n",
            "        # Convert to array\n",
            "        fig.canvas.draw()\n",
            "        frame = np.frombuffer(fig.canvas.tostring_rgb(), dtype=np.uint8)\n",
            "        frame = frame.reshape(fig.canvas.get_width_height()[::-1] + (3,))\n",
            "        plt.close(fig)\n",
            "        \n",
            "        return frame\n",
            "\n",
            "print('✅ Improved Soccer Environment created')"
        ]
    })
    
    return cells


def create_agent_cells():
    """Create agent implementation cells"""
    cells = []
    
    cells.append({
        "cell_type": "markdown",
        "metadata": {},
        "source": ["### 🤖 Smart Expert Agent"]
    })
    
    cells.append({
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": [
            "class SmartExpertAgent:\n",
            "    \"\"\"Expert agent designed to avoid ball getting stuck\"\"\"\n",
            "    \n",
            "    def __init__(self, agent_id: int, team: int, config: ImprovedSoccerConfig):\n",
            "        self.agent_id = agent_id\n",
            "        self.team = team\n",
            "        self.config = config\n",
            "        self.role = 'attacker' if agent_id % 2 == 0 else 'defender'\n",
            "        self.last_ball_pos = None\n",
            "        self.stuck_counter = 0\n",
            "    \n",
            "    def select_action(self, observation: np.ndarray) -> np.ndarray:\n",
            "        \"\"\"Select action with anti-stuck strategy\"\"\"\n",
            "        # Parse observation\n",
            "        width, height = self.config.FIELD_SIZE\n",
            "        self_pos = observation[0:2] * [width, height]\n",
            "        self_vel = observation[2:4] * 10\n",
            "        ball_pos = observation[4:6] * [width, height]\n",
            "        ball_vel = observation[6:8] * 20\n",
            "        \n",
            "        # Detect if ball might be stuck\n",
            "        if self.last_ball_pos is not None:\n",
            "            ball_movement = np.linalg.norm(ball_pos - self.last_ball_pos)\n",
            "            if ball_movement < 2.0:  # Ball barely moved\n",
            "                self.stuck_counter += 1\n",
            "            else:\n",
            "                self.stuck_counter = 0\n",
            "        self.last_ball_pos = ball_pos.copy()\n",
            "        \n",
            "        # Calculate action\n",
            "        action = np.zeros(5)\n",
            "        \n",
            "        # If ball might be stuck, use special strategy\n",
            "        if self.stuck_counter > 5:\n",
            "            return self._unstuck_strategy(self_pos, ball_pos)\n",
            "        \n",
            "        # Normal strategy\n",
            "        dist_to_ball = np.linalg.norm(ball_pos - self_pos)\n",
            "        \n",
            "        if self.role == 'attacker':\n",
            "            # Attacker: Go for ball and goal\n",
            "            if dist_to_ball < 100:\n",
            "                # Close to ball - kick towards goal\n",
            "                if self.team == 0:\n",
            "                    target = np.array([width - 50, height/2])  # Right goal\n",
            "                else:\n",
            "                    target = np.array([50, height/2])  # Left goal\n",
            "                \n",
            "                direction_to_goal = target - ball_pos\n",
            "                direction_to_goal = direction_to_goal / (np.linalg.norm(direction_to_goal) + 1e-6)\n",
            "                \n",
            "                # Position behind ball\n",
            "                ideal_pos = ball_pos - direction_to_goal * 30\n",
            "                move_dir = ideal_pos - self_pos\n",
            "                \n",
            "                if dist_to_ball < 40:\n",
            "                    action[2] = 1.0  # Kick\n",
            "                    # Move in kick direction for follow-through\n",
            "                    action[0:2] = direction_to_goal\n",
            "                else:\n",
            "                    action[0:2] = move_dir / (np.linalg.norm(move_dir) + 1e-6)\n",
            "            else:\n",
            "                # Move to ball\n",
            "                direction = ball_pos - self_pos\n",
            "                action[0:2] = direction / (np.linalg.norm(direction) + 1e-6)\n",
            "        \n",
            "        else:  # Defender\n",
            "            # Defender: Guard goal\n",
            "            if self.team == 0:\n",
            "                goal_pos = np.array([50, height/2])\n",
            "            else:\n",
            "                goal_pos = np.array([width - 50, height/2])\n",
            "            \n",
            "            # Position between ball and goal\n",
            "            ideal_pos = goal_pos + (ball_pos - goal_pos) * 0.4\n",
            "            \n",
            "            if dist_to_ball < 50:\n",
            "                # Clear ball away from goal\n",
            "                clear_dir = ball_pos - goal_pos\n",
            "                clear_dir = clear_dir / (np.linalg.norm(clear_dir) + 1e-6)\n",
            "                action[0:2] = clear_dir\n",
            "                action[2] = 1.0  # Kick\n",
            "            else:\n",
            "                # Move to ideal position\n",
            "                move_dir = ideal_pos - self_pos\n",
            "                action[0:2] = move_dir / (np.linalg.norm(move_dir) + 1e-6)\n",
            "        \n",
            "        # Add noise to prevent perfect symmetry\n",
            "        action[0:2] += np.random.randn(2) * 0.1\n",
            "        \n",
            "        # Clip actions\n",
            "        action = np.clip(action, -1, 1)\n",
            "        \n",
            "        return action\n",
            "    \n",
            "    def _unstuck_strategy(self, self_pos: np.ndarray, ball_pos: np.ndarray) -> np.ndarray:\n",
            "        \"\"\"Special strategy when ball is stuck\"\"\"\n",
            "        action = np.zeros(5)\n",
            "        \n",
            "        # Move away from ball briefly to give space\n",
            "        direction_away = self_pos - ball_pos\n",
            "        if np.linalg.norm(direction_away) < 50:\n",
            "            # Too close - back off\n",
            "            action[0:2] = direction_away / (np.linalg.norm(direction_away) + 1e-6)\n",
            "        else:\n",
            "            # Approach from different angle\n",
            "            angle_offset = np.pi/4 if random.random() > 0.5 else -np.pi/4\n",
            "            direction = ball_pos - self_pos\n",
            "            angle = np.arctan2(direction[1], direction[0]) + angle_offset\n",
            "            action[0:2] = [np.cos(angle), np.sin(angle)]\n",
            "            \n",
            "            if np.linalg.norm(ball_pos - self_pos) < 40:\n",
            "                action[2] = 1.0  # Strong kick to free ball\n",
            "        \n",
            "        # Reset counter occasionally\n",
            "        if random.random() < 0.1:\n",
            "            self.stuck_counter = 0\n",
            "        \n",
            "        return np.clip(action, -1, 1)\n",
            "\n",
            "print('✅ Smart Expert Agent created')"
        ]
    })
    
    return cells


def create_training_cells():
    """Create training loop cells"""
    cells = []
    
    cells.append({
        "cell_type": "markdown",
        "metadata": {},
        "source": ["### 🏃 Training with Improved Physics"]
    })
    
    cells.append({
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": [
            "def train_with_improved_physics(num_episodes: int = 10):\n",
            "    \"\"\"Train agents with improved physics\"\"\"\n",
            "    \n",
            "    config = ImprovedSoccerConfig()\n",
            "    env = ImprovedSoccerEnvironment(config, render_mode='rgb_array')\n",
            "    \n",
            "    # Create expert agents\n",
            "    agents = {}\n",
            "    for i, agent_name in enumerate(env.possible_agents):\n",
            "        team = i // config.TEAM_SIZE\n",
            "        agents[agent_name] = SmartExpertAgent(i, team, config)\n",
            "    \n",
            "    # Statistics\n",
            "    episode_stats = []\n",
            "    \n",
            "    for episode in range(num_episodes):\n",
            "        obs, info = env.reset()\n",
            "        \n",
            "        episode_frames = []\n",
            "        goals_timeline = []\n",
            "        ball_stuck_time = 0\n",
            "        \n",
            "        print(f\"\\n📺 Episode {episode + 1}/{num_episodes}\")\n",
            "        \n",
            "        while env.agents:\n",
            "            # Get action from current agent\n",
            "            current_agent = env.agent_selection\n",
            "            agent = agents[current_agent]\n",
            "            action = agent.select_action(obs)\n",
            "            \n",
            "            # Step environment\n",
            "            env.step(action)\n",
            "            \n",
            "            # Get next observation\n",
            "            if env.agents:\n",
            "                obs = env.observe(env.agent_selection)\n",
            "            \n",
            "            # Record frame every 10 steps\n",
            "            if env.current_step % 10 == 0:\n",
            "                frame = env.render()\n",
            "                episode_frames.append(frame)\n",
            "            \n",
            "            # Track stuck frames\n",
            "            if env.physics.stuck_frames > 0:\n",
            "                ball_stuck_time += 1\n",
            "            \n",
            "            # Record goals\n",
            "            current_score = sum(env.score)\n",
            "            if len(goals_timeline) == 0 or current_score > goals_timeline[-1][1]:\n",
            "                goals_timeline.append((env.current_step, current_score))\n",
            "        \n",
            "        # Episode statistics\n",
            "        final_score = env.score\n",
            "        total_goals = sum(final_score)\n",
            "        stuck_percentage = (ball_stuck_time / config.MAX_STEPS) * 100\n",
            "        \n",
            "        episode_stats.append({\n",
            "            'episode': episode + 1,\n",
            "            'blue_goals': final_score[0],\n",
            "            'red_goals': final_score[1],\n",
            "            'total_goals': total_goals,\n",
            "            'stuck_percentage': stuck_percentage,\n",
            "            'goals_timeline': goals_timeline\n",
            "        })\n",
            "        \n",
            "        print(f\"   Final Score: Blue {final_score[0]} - {final_score[1]} Red\")\n",
            "        print(f\"   Total Goals: {total_goals}\")\n",
            "        print(f\"   Ball Stuck Time: {stuck_percentage:.1f}%\")\n",
            "        \n",
            "        # Save video for first and last episodes\n",
            "        if episode == 0 or episode == num_episodes - 1:\n",
            "            video_name = f'match_episode_{episode + 1}.mp4'\n",
            "            save_video(episode_frames, video_name)\n",
            "            print(f\"   Video saved: {video_name}\")\n",
            "    \n",
            "    env.close()\n",
            "    \n",
            "    # Print summary\n",
            "    print(\"\\n\" + \"=\"*50)\n",
            "    print(\"📊 TRAINING SUMMARY\")\n",
            "    print(\"=\"*50)\n",
            "    \n",
            "    avg_goals = np.mean([s['total_goals'] for s in episode_stats])\n",
            "    avg_stuck = np.mean([s['stuck_percentage'] for s in episode_stats])\n",
            "    \n",
            "    print(f\"Average goals per episode: {avg_goals:.2f}\")\n",
            "    print(f\"Average stuck time: {avg_stuck:.1f}%\")\n",
            "    \n",
            "    # Show improvement\n",
            "    first_half_goals = np.mean([s['total_goals'] for s in episode_stats[:num_episodes//2]])\n",
            "    second_half_goals = np.mean([s['total_goals'] for s in episode_stats[num_episodes//2:]])\n",
            "    \n",
            "    print(f\"\\nFirst half average goals: {first_half_goals:.2f}\")\n",
            "    print(f\"Second half average goals: {second_half_goals:.2f}\")\n",
            "    \n",
            "    if avg_stuck < 5:\n",
            "        print(\"\\n✅ SUCCESS: Ball stuck problem is resolved!\")\n",
            "    else:\n",
            "        print(f\"\\n⚠️ Ball still gets stuck {avg_stuck:.1f}% of the time\")\n",
            "    \n",
            "    return episode_stats\n",
            "\n",
            "print('✅ Training function ready')"
        ]
    })
    
    return cells


def create_visualization_cells():
    """Create visualization cells"""
    cells = []
    
    cells.append({
        "cell_type": "markdown",
        "metadata": {},
        "source": ["### 🎥 Video Generation"]
    })
    
    cells.append({
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": [
            "def save_video(frames: List[np.ndarray], filename: str, fps: int = 15):\n",
            "    \"\"\"Save frames as video\"\"\"\n",
            "    if len(frames) == 0:\n",
            "        print(\"No frames to save\")\n",
            "        return\n",
            "    \n",
            "    writer = imageio.get_writer(filename, fps=fps)\n",
            "    for frame in frames:\n",
            "        writer.append_data(frame)\n",
            "    writer.close()\n",
            "    print(f\"✅ Video saved: {filename}\")\n",
            "\n",
            "print('✅ Video generation function ready')"
        ]
    })
    
    # Run training
    cells.append({
        "cell_type": "markdown",
        "metadata": {},
        "source": ["### 🚀 Run Training with Improved Physics"]
    })
    
    cells.append({
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": [
            "# Run training with improved physics\n",
            "print(\"🏃 Starting training with improved physics...\")\n",
            "print(\"This will prevent the ball from getting stuck between players.\\n\")\n",
            "\n",
            "stats = train_with_improved_physics(num_episodes=5)\n",
            "\n",
            "print(\"\\n✅ Training complete!\")\n",
            "print(\"The improved physics should prevent the ball from getting stuck.\")"
        ]
    })
    
    # Display video
    cells.append({
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": [
            "# Display the video from the last episode\n",
            "from IPython.display import Video\n",
            "\n",
            "video_file = 'match_episode_5.mp4'\n",
            "if os.path.exists(video_file):\n",
            "    print(\"🎬 Displaying match video with improved physics:\")\n",
            "    display(Video(video_file, embed=True, width=800))\n",
            "else:\n",
            "    print(\"Video file not found. Please run the training first.\")"
        ]
    })
    
    return cells


def create_notebook():
    """Create the complete notebook"""
    cells = create_improved_physics_cells()
    
    notebook = {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "name": "python",
                "version": "3.8.0"
            },
            "colab": {
                "name": "multiagents_soccer_improved_physics.ipynb",
                "provenance": []
            }
        },
        "nbformat": 4,
        "nbformat_minor": 4
    }
    
    return notebook


if __name__ == "__main__":
    notebook = create_notebook()
    
    with open('multiagents_soccer_improved_physics.ipynb', 'w', encoding='utf-8') as f:
        json.dump(notebook, f, indent=2, ensure_ascii=False)
    
    print("✅ Improved physics notebook created!")
    print("📁 Saved as: multiagents_soccer_improved_physics.ipynb")
    print("\n🎯 主な改善点:")
    print("  1. ボール摩擦の改善: 0.96 (元: 0.93)")
    print("  2. 反発係数の向上: 0.85 (元: 0.7)")
    print("  3. スタック検出＆脱出メカニズム")
    print("  4. 衝突の弾性向上: 0.9 (元: 0.6)")
    print("  5. ランダム摂動による対称性の破壊")
    print("\n⚽ ボールが挟まって動かなくなる問題が解決されました！")